import "./imports"
import "@effect-ts-app/boilerplate-prelude/_ext/Prelude.ext"
import "@effect-ts-app/boilerplate-prelude/_ext/RArray"
// import "@effect-ts-app/boilerplate-prelude/_ext/Object"
import "@effect-ts-app/core/fluent/_ext/awesome/node"
import "@effect-ts-app/core/_global"
import "@effect-ts-app/core/Prelude"