/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const afterAll: typeof import('@effect-app/infra/vitest')['afterAll']
  const afterEach: typeof import('@effect-app/infra/vitest')['afterEach']
  const assert: typeof import('@effect-app/infra/vitest')['assert']
  const beforeAll: typeof import('@effect-app/infra/vitest')['beforeAll']
  const beforeEach: typeof import('@effect-app/infra/vitest')['beforeEach']
  const chai: typeof import('vitest')['chai']
  const createRandomInstance: typeof import('@effect-app/infra/vitest')['createRandomInstance']
  const createRandomInstanceI: typeof import('@effect-app/infra/vitest')['createRandomInstanceI']
  const describe: typeof import('@effect-app/infra/vitest')['describe']
  const expect: typeof import('@effect-app/infra/vitest')['expect']
  const it: typeof import('@effect-app/infra/vitest')['it']
  const layer: typeof import('@effect-app/infra/vitest')['layer']
  const suite: typeof import('@effect-app/infra/vitest')['suite']
  const test: typeof import('@effect-app/infra/vitest')['test']
  const vi: typeof import('vitest')['vi']
  const vitest: typeof import('vitest')['vitest']
}
